import json
from pathlib import Path
from datetime import datetime, timezone
from typing import Any, Dict, List

REPORTS_DIR = Path("reports")

#los que salen de los scripts de ataque activos
ACTIVE_FINDINGS_FILE = REPORTS_DIR / "findings.jsonl"
#hallazgos que salen del observador pasivo de mitmproxy/cerberus
CERBERUS_FINDINGS_FILE = REPORTS_DIR / "cerberus_findings.jsonl"
#informe final 
REPORT_FILE = REPORTS_DIR / "audit_report.md"


def load_jsonl_file(path: Path) -> List[Dict[str, Any]]:

    if not path.exists():
        return []
    findings: List[Dict[str, Any]] = []

    with path.open("r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()

            if not line:
                continue

            findings.append(json.loads(line))

    return findings


def severity_rank(severity: str) -> int: #convierte la severidad en numero para poder ordenar los fallos.

    ranks = {
        "Critical": 4,
        "High": 3,
        "Medium": 2,
        "Low": 1
    }

    return ranks.get(severity, 0)


def finding_source_label(finding: Dict[str, Any]) -> str: #devuelve un nombre legible para saber de donde salio el hallazgo.
    
    source = finding.get("source", "unknown")

    if source == "automated_attack_script":
        return "Active attack module"

    if source == "cerberus_mitmproxy":
        return "Cerberus proxy observer"

    return str(source)


def confirmed_text(finding: Dict[str, Any]) -> str: #pasa el booleano confirmed a texto para el informe.

    confirmed = finding.get("confirmed", False)

    if confirmed:
        return "Confirmed"

    return "Observed"


def generate_report() -> None: #genera el informe markdown juntando ataques activos y observaciones de cerberus.

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    active_findings = load_jsonl_file(ACTIVE_FINDINGS_FILE)
    cerberus_findings = load_jsonl_file(CERBERUS_FINDINGS_FILE)

    all_findings = active_findings + cerberus_findings

    all_findings.sort(
        key=lambda finding: (
            finding.get("confirmed", False),
            severity_rank(finding.get("severity", "Low"))
        ),
        reverse=True
    )

    confirmed_findings = [
        finding for finding in all_findings
        if finding.get("confirmed", False)
    ]

    observed_findings = [
        finding for finding in all_findings
        if not finding.get("confirmed", False)
    ]

    generated_at = datetime.now(timezone.utc).isoformat()

    lines: List[str] = []

    lines.append("# Steamworks DAST Lab - Technical Audit Report")
    lines.append("")
    lines.append(f"Generated at: {generated_at}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(  #para poner algo provisonal
        "This report summarizes the findings produced by the Steamworks DAST "
        "Lab. It combines confirmed vulnerabilities from active attack modules "
        "with additional observations generated by the Cerberus mitmproxy "
        "observer."
    )
    lines.append("")
    lines.append(f"- Active attack findings: {len(active_findings)}")
    lines.append(f"- Cerberus proxy findings: {len(cerberus_findings)}")
    lines.append(f"- Total findings: {len(all_findings)}")
    lines.append(f"- Confirmed findings: {len(confirmed_findings)}")
    lines.append(f"- Observed findings: {len(observed_findings)}")
    lines.append("")

    if not all_findings:
        lines.append("No findings were found. Run the attack scripts first.")
        REPORT_FILE.write_text("\n".join(lines), encoding="utf-8")
        print(f"Report generated: {REPORT_FILE}")
        return

    #tabla rapida con todos los hallazgos

    lines.append("## Findings Overview")
    lines.append("")
    lines.append(
        "| # | Source | Vulnerability | Severity | OWASP Category | Status | Endpoint |"
    )
    lines.append(
        "|---|---|---|---|---|---|---|"
    )

    for index, finding in enumerate(all_findings, start=1):
        lines.append(
            f"| {index} "
            f"| {finding_source_label(finding)} "
            f"| {finding.get('vulnerability', '')} "
            f"| {finding.get('severity', '')} "
            f"| {finding.get('owasp_category', '')} "
            f"| {confirmed_text(finding)} "
            f"| `{finding.get('endpoint', '')}` |"
        )

    lines.append("")

    #detalle de los fallos confirmados por ataques activos

    lines.append("## Confirmed Findings from Active Attack Modules")
    lines.append("")

    if not active_findings:
        lines.append("No active attack findings were generated.")
        lines.append("")
    else:
        for index, finding in enumerate(active_findings, start=1):
            append_finding_details(lines, index, finding)

    #detalle de lo que vio cerberus mirando el trafico

    lines.append("## Observations from Cerberus Proxy")
    lines.append("")

    if not cerberus_findings:
        lines.append("No Cerberus proxy findings were generated.")
        lines.append("")
    else:
        for index, finding in enumerate(cerberus_findings, start=1):
            append_finding_details(lines, index, finding)

    REPORT_FILE.write_text("\n".join(lines), encoding="utf-8")

    print(f"Report generated: {REPORT_FILE}")


def append_finding_details(
    lines: List[str],
    index: int,
    finding: Dict[str, Any]
) -> None:
    """
    añade un hallazgo concreto al informe.
    """

    lines.append(f"### {index}. {finding.get('vulnerability', '')}")
    lines.append("")
    lines.append(f"**Source:** {finding_source_label(finding)}")
    lines.append("")
    lines.append(f"**Severity:** {finding.get('severity', '')}")
    lines.append("")
    lines.append(f"**OWASP Category:** {finding.get('owasp_category', '')}")
    lines.append("")
    lines.append(f"**Affected endpoint:** `{finding.get('endpoint', '')}`")
    lines.append("")
    lines.append(f"**Status:** `{confirmed_text(finding)}`")
    lines.append("")
    lines.append("**Evidence:**")
    lines.append("")
    lines.append("```json")
    lines.append(
        json.dumps(
            finding.get("evidence", {}),
            indent=2,
            ensure_ascii=False
        )
    )
    lines.append("```")
    lines.append("")
    lines.append("**Recommended mitigation:**")
    lines.append("")
    lines.append(finding.get("mitigation", ""))
    lines.append("")


if __name__ == "__main__":
    generate_report()
